USE [master]
GO

/****** Object:  Database [GameLibraryDB]    Script Date: 1/10/2024 4:40:45 PM ******/
CREATE DATABASE [GameLibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GameLibraryDB', FILENAME = N'/var/opt/mssql/data/GameLibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'GameLibraryDB_log', FILENAME = N'/var/opt/mssql/data/GameLibraryDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GameLibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GameLibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GameLibraryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GameLibraryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GameLibraryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GameLibraryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GameLibraryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GameLibraryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GameLibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GameLibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GameLibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GameLibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GameLibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GameLibraryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GameLibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GameLibraryDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GameLibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GameLibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GameLibraryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GameLibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GameLibraryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GameLibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GameLibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GameLibraryDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GameLibraryDB] SET  MULTI_USER 
GO

ALTER DATABASE [GameLibraryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GameLibraryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GameLibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GameLibraryDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GameLibraryDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GameLibraryDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GameLibraryDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [GameLibraryDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GameLibraryDB] SET  READ_WRITE 
GO


