USE [GameLibraryDB_yangnj]
GO

/* Create Database Tables */
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--Studio Table
CREATE TABLE [dbo].[Studio](
	[Name] [varchar](50) NOT NULL,
	[Website] [varchar](75) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Studio] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--Game Table
CREATE TABLE [dbo].[Game](
	[Name] [varchar](50) NOT NULL,
	[ReleaseDate] [date] NOT NULL,
	[Description] [varchar](400) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Studio] [int] NOT NULL,
 CONSTRAINT [PK_Game] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Game]  WITH CHECK ADD  CONSTRAINT [FK_Game_Studio] FOREIGN KEY([Studio])
REFERENCES [dbo].[Studio] ([ID])
GO

ALTER TABLE [dbo].[Game] CHECK CONSTRAINT [FK_Game_Studio]
GO

--Platform Table
CREATE TABLE [dbo].[Platform](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Website] [varchar](75) NULL,
 CONSTRAINT [PK_Platform] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--Genre Table
CREATE TABLE [dbo].[Genre](
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Genre] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--Notes
CREATE TABLE [dbo].[Notes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[text] [varchar](1000) NULL,
	[GameID] [int] NOT NULL,
 CONSTRAINT [PK_Notes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Notes]  WITH CHECK ADD  CONSTRAINT [FK_Notes_Game] FOREIGN KEY([Id])
REFERENCES [dbo].[Game] ([ID])
GO

--Reviews Table
CREATE TABLE [dbo].[Reviews](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](500) NULL,
	[NumberOfStars] [smallint] NOT NULL,
	[GameID] [int] NOT NULL,
 CONSTRAINT [PK_Reviews] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Notes] CHECK CONSTRAINT [FK_Notes_Game]
GO

--StudioOnPlatform Table
CREATE TABLE [dbo].[StudioOnPlatform](
	[Studio] [int] NOT NULL,
	[Platform] [int] NOT NULL,
 CONSTRAINT [PK_StudioOnPlatform] PRIMARY KEY CLUSTERED 
(
	[Studio] ASC,
	[Platform] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[StudioOnPlatform]  WITH CHECK ADD FOREIGN KEY([Platform])
REFERENCES [dbo].[Platform] ([ID])
GO

ALTER TABLE [dbo].[StudioOnPlatform]  WITH CHECK ADD FOREIGN KEY([Studio])
REFERENCES [dbo].[Studio] ([ID])
GO

ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD  CONSTRAINT [FK_Reviews_Game] FOREIGN KEY([Id])
REFERENCES [dbo].[Game] ([ID])
GO

ALTER TABLE [dbo].[Reviews] CHECK CONSTRAINT [FK_Reviews_Game]
GO

ALTER TABLE [dbo].[Reviews]  WITH CHECK ADD  CONSTRAINT [CK_Reviews] CHECK  (([NumberOfStars]>=(0) AND [NumberOfStars]<=(5)))
GO

ALTER TABLE [dbo].[Reviews] CHECK CONSTRAINT [CK_Reviews]
GO

--GameOnPlatform Table
CREATE TABLE [dbo].[GameOnPlatform](
	[Game] [int] NOT NULL,
	[Platform] [int] NOT NULL,
 CONSTRAINT [PK_GameOnPlatform] PRIMARY KEY CLUSTERED 
(
	[Game] ASC,
	[Platform] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--GameHasGenre Table
CREATE TABLE [dbo].[GameHasGenre](
	[GameID] [int] NOT NULL,
	[GenreName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_GameHasGenre] PRIMARY KEY CLUSTERED 
(
	[GameID] ASC,
	[GenreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


